=== Open-Inflation/chizhik_api/tests/__snapshots__/ClassCatalog.delivery_search.schema.json
{
  "type": "object",
  "required": [
    "categories",
    "products",
    "query_type",
    "search_query_id"
  ],
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "properties": {
    "categories": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "id",
          "name",
          "parent_name",
          "type"
        ],
        "properties": {
          "id": {
            "type": "string",
            "enum": [
              "264C39231",
              "264C39180"
            ]
          },
          "main_name": {
            "type": "string",
            "enum": [
              "Основной каталог"
            ]
          },
          "name": {
            "type": "string",
            "j2sEnumRejected": true
          },
          "parent_id": {
            "type": "string",
            "enum": [
              "264C39228"
            ]
          },
          "parent_name": {
            "type": "string",
            "enum": [
              "Напитки",
              "Мясная гастрономия"
            ]
          },
          "type": {
            "type": "string",
            "enum": [
              "subcategory"
            ]
          }
        }
      }
    },
    "detail": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "ctx",
          "input",
          "loc",
          "msg",
          "type",
          "url"
        ],
        "properties": {
          "ctx": {
            "type": "object",
            "required": [
              "min_length"
            ],
            "properties": {
              "min_length": {
                "type": "integer"
              }
            }
          },
          "input": {
            "type": "string"
          },
          "loc": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "msg": {
            "type": "string"
          },
          "type": {
            "type": "string"
          },
          "url": {
            "type": "string",
            "format": "uri"
          }
        }
      }
    },
    "products": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "badges",
          "boost_type",
          "cpd_labels",
          "features",
          "has_age_restriction",
          "image_links",
          "initial_weight_step",
          "is_available",
          "is_large_card",
          "labels",
          "max_qty_per_order",
          "median_price",
          "min_weight",
          "name",
          "orange_loyalty_points",
          "plu",
          "price_piece_unit",
          "prices",
          "product_advert",
          "promo",
          "property_clarification",
          "rating",
          "step",
          "stickers",
          "stock_limit",
          "uom"
        ],
        "properties": {
          "badges": {
            "type": "array",
            "items": {}
          },
          "boost_type": {
            "type": "null"
          },
          "cpd_labels": {
            "type": "null"
          },
          "features": {
            "type": "null"
          },
          "has_age_restriction": {
            "type": "boolean"
          },
          "image_links": {
            "type": "object",
            "required": [
              "normal",
              "small"
            ],
            "properties": {
              "normal": {
                "type": "array",
                "items": {
                  "type": "string",
                  "format": "uri"
                }
              },
              "small": {
                "type": "array",
                "items": {
                  "type": "string",
                  "format": "uri"
                }
              }
            }
          },
          "initial_weight_step": {
            "type": "string",
            "j2sEnumRejected": true
          },
          "is_available": {
            "type": "boolean"
          },
          "is_large_card": {
            "type": "null"
          },
          "labels": {
            "type": "null"
          },
          "max_qty_per_order": {
            "type": "null"
          },
          "median_price": {
            "type": "null"
          },
          "min_weight": {
            "type": "string",
            "j2sEnumRejected": true
          },
          "name": {
            "type": "string",
            "j2sEnumRejected": true
          },
          "orange_loyalty_points": {
            "type": "integer"
          },
          "plu": {
            "type": "integer"
          },
          "price_piece_unit": {
            "type": "null"
          },
          "prices": {
            "type": "object",
            "required": [
              "cpd_promo_price",
              "cpd_promo_price_from_sum_cart",
              "discount",
              "regular"
            ],
            "properties": {
              "cpd_promo_price": {
                "type": "null"
              },
              "cpd_promo_price_from_sum_cart": {
                "type": "null"
              },
              "discount": {
                "type": "null"
              },
              "regular": {
                "type": "string",
                "j2sEnumRejected": true
              }
            }
          },
          "product_advert": {
            "type": "null"
          },
          "promo": {
            "type": "null"
          },
          "property_clarification": {
            "type": "string",
            "enum": [
              "1.5 л",
              "500 г",
              "250 г",
              "330 г",
              "50 г",
              "80 г",
              "70 г",
              "150 г",
              "1 л",
              "500 мл",
              "108 г"
            ]
          },
          "rating": {
            "anyOf": [
              {
                "type": "object",
                "required": [
                  "rates_count",
                  "rating_average"
                ],
                "properties": {
                  "rates_count": {
                    "type": "integer"
                  },
                  "rating_average": {
                    "type": "number"
                  }
                }
              },
              {
                "type": "null"
              }
            ]
          },
          "step": {
            "type": "string",
            "j2sEnumRejected": true
          },
          "stickers": {
            "type": "null"
          },
          "stock_limit": {
            "type": "string",
            "j2sEnumRejected": true
          },
          "uom": {
            "type": "string",
            "enum": [
              "шт"
            ]
          }
        }
      }
    },
    "query_type": {
      "type": "string",
      "enum": [
        "strict"
      ]
    },
    "search_query_id": {
      "type": "string",
      "format": "uuid"
    }
  }
}

=== Open-Inflation/chizhik_api/tests/__snapshots__/ClassCatalog.delivery_search.json
{
  "search_query_id": "dce3fdb5-b9d4-48e4-a87f-9240e11846b3",
  "query_type": "strict",
  "products": [
    {
      "plu": 5969,
      "name": "Напиток Coca-Cola газированный 1л",
      "image_links": {
        "small": [
          "https://catalog-images.x5static.net/product/2148280-main/320x320.jpeg"
        ],
        "normal": [
          "https://catalog-images.x5static.net/product/2148280-main/800x800.jpeg"
        ]
      },
      "uom": "шт",
      "step": "1.0",
      "rating": {
        "rating_average": 4.85,
        "rates_count": 8493
      },
      "promo": null,
      "prices": {
        "regular": "119.0",
        "discount": null,
        "cpd_promo_price": null,
        "cpd_promo_price_from_sum_cart": null
      },
      "labels": null,
      "cpd_labels": null,
      "property_clarification": "1 л",
      "has_age_restriction": false,
      "stock_limit": "32.00",
      "median_price": null,
      "product_advert": null,
      "is_large_card": null,
      "boost_type": null,
      "badges": [],
      "initial_weight_step": "1.0",
      "min_weight": "1.0",
      "max_qty_per_order": null,
      "orange_loyalty_points": 70,
      "is_available": true,
      "price_piece_unit": null,
      "stickers": null,
      "features": null
    },
    {
      "plu": 4435075,
      "name": "Напиток FUN UP Кола газированный 1,5л",
      "image_links": {
        "small": [
          "https://catalog-images.x5static.net/product/2127847-main/320x320.jpeg?updated_at=2026-01-19T11:06:52.368Z"
        ],
        "normal": [
          "https://catalog-images.x5static.net/product/2127847-main/800x800.jpeg?updated_at=2026-01-19T11:06:52.368Z"
        ]
      },
      "uom": "шт",
      "step": "1.0",
      "rating": null,
      "promo": null,
      "prices": {
        "regular": "89.0",
        "discount": null,
        "cpd_promo_price": null,
        "cpd_promo_price_from_sum_cart": null
      },
      "labels": null,
      "cpd_labels": null,
      "property_clarification": "1.5 л",
      "has_age_restriction": false,
      "stock_limit": "35.00",
      "median_price": null,
      "product_advert": null,
      "is_large_card": null,
      "boost_type": null,
      "badges": [],
      "initial_weight_step": "1.0",
      "min_weight": "1.0",
      "max_qty_per_order": null,
      "orange_loyalty_points": 62,
      "is_available": true,
      "price_piece_unit": null,
      "stickers": null,
      "features": null
    },
    {
      "plu": 4435074,
      "name": "Напиток FUN UP Кола без сахара газированный 1,5л",
      "image_links": {
        "small": [
          "https://catalog-images.x5static.net/product/2111640-main/320x320.jpeg?updated_at=2025-12-01T17:49:30.146Z"
        ],
        "normal": [
          "https://catalog-images.x5static.net/product/2111640-main/800x800.jpeg?updated_at=2025-12-01T17:49:30.146Z"
        ]
      },
      "uom": "шт",
      "step": "1.0",
      "rating": {
        "rating_average": 2.9,
        "rates_count": 322
      },
      "promo": null,
      "prices": {
        "regular": "89.0",
        "discount": null,
        "cpd_promo_price": null,
        "cpd_promo_price_from_sum_cart": null
      },
      "labels": null,
      "cpd_labels": null,
      "property_clarification": "1.5 л",
      "has_age_restriction": false,
      "stock_limit": "44.00",
      "median_price": null,
      "product_advert": null,
      "is_large_card": null,
      "boost_type": null,
      "badges": [],
      "initial_weight_step": "1.0",
      "min_weight": "1.0",
      "max_qty_per_order": null,
      "orange_loyalty_points": 62,
      "is_available": true,
      "price_piece_unit": null,
      "stickers": null,
      "features": null
    },
    {
      "plu": 4320707,
      "name": "Напиток FUN UP Кола без сахара газированный 0.5л",
      "image_links": {
        "small": [
          "https://catalog-images.x5static.net/product/1578018-main/320x320.jpeg?updated_at=2024-12-05T15:19:41.317Z"
        ],
        "normal": [
          "https://catalog-images.x5static.net/product/1578018-main/800x800.jpeg?updated_at=2024-12-05T15:19:41.317Z"
        ]
      },
      "uom": "шт",
      "step": "1.0",
      "rating": {
        "rating_average": 0.0,
        "rates_count": 309
      },
      "promo": null,
      "prices": {
        "regular": "39.0",
        "discount": null,
        "cpd_promo_price": null,
        "cpd_promo_price_from_sum_cart": null
      },
      "labels": null,
      "cpd_labels": null,
      "property_clarification": "500 мл",
      "has_age_restriction": false,
      "stock_limit": "152.00",
      "median_price": null,
      "product_advert": null,
      "is_large_card": null,
      "boost_type": null,
      "badges": [],
      "initial_weight_step": "1.0",
      "min_weight": "1.0",
      "max_qty_per_order": null,
      "orange_loyalty_points": 27,
      "is_available": true,
      "price_piece_unit": null,
      "stickers": null,
      "features": null
    },
    {
      "plu": 4416148,
      "name": "Карамель Chupa Chups Рarty Time Mix со вкусом Кола и Вишня 108г",
      "image_links": {
        "small": [
          "https://catalog-images.x5static.net/product/2028480-main/320x320.jpeg?updated_at=2025-09-24T18:00:37.949Z"
        ],
        "normal": [
          "https://catalog-images.x5static.net/product/2028480-main/800x800.jpeg?updated_at=2025-09-24T18:00:37.949Z"
        ]
      },
      "uom": "шт",
      "step": "1.0",
      "rating": {
        "rating_average": 0.0,
        "rates_count": 63
      },
      "promo": null,
      "prices": {
        "regular": "59.0",
        "discount": null,
        "cpd_promo_price": null,
        "cpd_promo_price_from_sum_cart": null
      },
      "labels": null,
      "cpd_labels": null,
      "property_clarification": "108 г",
      "has_age_restriction": false,
      "stock_limit": "23.00",
      "median_price": null,
      "product_advert": null,
      "is_large_card": null,
      "boost_type": null,
      "badges": [],
      "initial_weight_step": "1.0",
      "min_weight": "1.0",
      "max_qty_per_order": null,
      "orange_loyalty_points": 41,
      "is_available": true,
      "price_piece_unit": null,
      "stickers": null,
      "features": null
    },
    {
      "plu": 4413972,
      "name": "Напиток Добрый Кола пониженной калорийности газированный 1.5л",
      "image_links": {
        "small": [
          "https://catalog-images.x5static.net/product/2035800-main/320x320.jpeg"
        ],
        "normal": [
          "https://catalog-images.x5static.net/product/2035800-main/800x800.jpeg",
          "https://catalog-images.x5static.net/product/0ec4178ea335c8dfe6f1d80a495e0911-additional/800x800.jpeg",
          "https://catalog-images.x5static.net/product/666077bdd534eed859b82895324ee017-additional/800x800.jpeg",
          "https://catalog-images.x5static.net/product/9fb91f819d3de5af2d338178c031ed2c-additional/800x800.jpeg"
        ]
      },
      "uom": "шт",
      "step": "1.0",
      "rating": {
        "rating_average": 0.0,
        "rates_count": 93
      },
      "promo": null,
      "prices": {
        "regular": "129.0",
        "discount": null,
        "cpd_promo_price": null,
        "cpd_promo_price_from_sum_cart": null
      },
      "labels": null,
      "cpd_labels": null,
      "property_clarification": "1.5 л",
      "has_age_restriction": false,
      "stock_limit": "27.00",
      "median_price": null,
      "product_advert": null,
      "is_large_card": null,
      "boost_type": null,
      "badges": [],
      "initial_weight_step": "1.0",
      "min_weight": "1.0",
      "max_qty_per_order": null,
      "orange_loyalty_points": 70,
      "is_available": true,
      "price_piece_unit": null,
      "stickers": null,
      "features": null
    }
  ],
  "categories": [
    {
      "id": "264C39231",
      "type": "subcategory",
      "name": "Газированные напитки",
      "parent_name": "Напитки",
      "parent_id": "264C39228",
      "main_name": "Основной каталог"
    }
  ]
}
